spring:
  application:
    name: gateway
  datasource:
    url: jdbc:mysql://localhost:3306/xhzh?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: XinHong12345
    driver-class-name: com.mysql.jdbc.Driver
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    authService:
      #zuul转发请求时会丢失authorization的信息
      sensitive-headers:
      custom-sensitive-headers: true
      path: /auth/**
      serviceId: authService
    service-connection:
      #zuul转发请求时会丢失authorization的信息
      sensitive-headers:
      custom-sensitive-headers: true
      path: /connect/**
      serviceId: service-connection
    service-spd:
      #zuul转发请求时会丢失authorization的信息
      sensitive-headers:
      custom-sensitive-headers: true
      path: /spd/**
      serviceId: service-spd
    service-etcr:
      #zuul转发请求时会丢失authorization的信息
      sensitive-headers:
      custom-sensitive-headers: true
      path: /etcr/**
      serviceId: service-etcr
    service-MQ:
      #zuul转发请求时会丢失authorization的信息
      sensitive-headers:
      custom-sensitive-headers: true
      path: /mq/**
      serviceId: service-MQ
    service-lightning:
      #zuul转发请求时会丢失authorization的信息
      sensitive-headers:
      custom-sensitive-headers: true
      path: /lightning/**
      serviceId: service-lightning
    service-static:
      #zuul转发请求时会丢失authorization的信息
      sensitive-headers:
      custom-sensitive-headers: true
      path: /static/**
      serviceId: service-static
    service-rsws:
      #zuul转发请求时会丢失authorization的信息
      sensitive-headers:
      custom-sensitive-headers: true
      path: /rsws/**
      serviceId: service-rsws
    service-svt:
      #zuul转发请求时会丢失authorization的信息
      sensitive-headers:
      custom-sensitive-headers: true
      path: /svt/**
      serviceId: service-svt
    service-hc:
      #zuul转发请求时会丢失authorization的信息
      sensitive-headers:
      custom-sensitive-headers: true
      path: /hc/**
      serviceId: service-hc
    service-stray:
      #zuul转发请求时会丢失authorization的信息
      sensitive-headers:
      custom-sensitive-headers: true
      path: /stray/**
      serviceId: service-stray
    service-cat:
      #zuul转发请求时会丢失authorization的信息
      sensitive-headers:
      custom-sensitive-headers: true
      path: /cat/**
      serviceId: service-cat
    service-total:
      #zuul转发请求时会丢失authorization的信息
      sensitive-headers:
      custom-sensitive-headers: true
      path: /total/**
      serviceId: service-total
eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://test:test@localhost:8081/eureka/
server:
  port: 8080
  session:
    timeout: 0
security:
  user:
    name: test
    password: test
logging:
  #pattern:
    #格式化，只能输出日期和内容
    #console: "%d - %msg%n"
  path: /usr/logs
  file: /usr/logs/gateway.log