server:
  port: 8081
  tomcat:
    max-threads: 10
eureka:
  server:
    enableSelfPreservation : true
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
security:
  user:
    name: test
    password: test
logging:
  #pattern:
  #格式化，只能输出日期和内容
  #console: "%d - %msg%n"
  path: /usr/logs
  file: /usr/logs/eureka.log